include(FindPackageHandleStandardArgs)

file(
	GLOB
	COIN_INCLUDE_PATHS
	$ENV{COINDIR}/include
	$ENV{COIN3DDIR}/include
	$ENV{HOME}/include
	/usr/local/include
	/usr/include/Coin*
	/usr/include
	$ENV{SystemDrive}/Coin*/include
	$ENV{ProgramW6432}/Coin*/include
	$ENV{ProgramFiles}/Coin*/include
)

file(
	GLOB
	COIN_LIBRARY_PATHS
	$ENV{COINDIR}/lib
	$ENV{COIN3DDIR}/lib
	$ENV{HOME}/lib
	/usr/local/lib
	/usr/lib
	$ENV{SystemDrive}/Coin*/lib
	$ENV{ProgramW6432}/Coin*/lib
	$ENV{ProgramFiles}/Coin*/lib
)

find_path(
	COIN_INCLUDE_DIRS
	NAMES
	Inventor/So.h
	HINTS
	${COIN_INCLUDE_PATHS}
)

find_library(
	COIN_LIBRARY_DEBUG
	NAMES
	Coind coin2d coin3d
	HINTS
	${COIN_LIBRARY_PATHS}
)

find_library(
	COIN_LIBRARY_RELEASE
	NAMES
	Coin coin2 coin3
	HINTS
	${COIN_LIBRARY_PATHS}
)

set(COIN_DEFINITIONS -DCOIN_NOT_DLL)

if(COIN_LIBRARY_DEBUG AND NOT COIN_LIBRARY_RELEASE)
	set(COIN_LIBRARIES ${COIN_LIBRARY_DEBUG})
endif(COIN_LIBRARY_DEBUG AND NOT COIN_LIBRARY_RELEASE)

if(COIN_LIBRARY_RELEASE AND NOT COIN_LIBRARY_DEBUG)
	set(COIN_LIBRARIES ${COIN_LIBRARY_RELEASE})
endif(COIN_LIBRARY_RELEASE AND NOT COIN_LIBRARY_DEBUG)

if(COIN_LIBRARY_DEBUG AND COIN_LIBRARY_RELEASE)
	set(COIN_LIBRARIES debug ${COIN_LIBRARY_DEBUG} optimized ${COIN_LIBRARY_RELEASE})
endif(COIN_LIBRARY_DEBUG AND COIN_LIBRARY_RELEASE)

find_package_handle_standard_args(
	Coin
	DEFAULT_MSG
	COIN_INCLUDE_DIRS
	COIN_LIBRARIES
)

mark_as_advanced(
	COIN_DEFINITIONS
	COIN_INCLUDE_DIRS
	COIN_LIBRARIES
	COIN_LIBRARY_DEBUG
	COIN_LIBRARY_RELEASE
) 
